more sophisticated model serve

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -167,15 +167,21 @@ tasks:
       - task: data:docker-network
     cmds:
       - |
-        docker inspect --format "{{`{{.State.Running}}`}}" dataweek_model || echo "inspect dataweek_model: not found"
-        docker ps -a
-        docker run {{.DOCKER_ARGS}} --rm -d --name dataweek_model \
-          --network {{.MODEL_DOCKER_NETWORK}} \
-          -v {{.PWD}}/{{.MODEL_DIR}}/:/graph \
-          {{.FUSEKI_IMAGE}} \
-          /jena-fuseki/fuseki-server --tdb2 --file=/graph/{{.GRAPH_FILE}}.nt /model || echo "inspect dataweek_model: not found"
-        docker ps -a
-        docker inspect --format "{{`{{.State.Running}}`}}" dataweek_model
+        while [ $( docker inspect --format "{{`{{.State.Status}}`}}" dataweek_model )" = "created" ]
+        do
+          echo "dataweek_model created waiting for it to run"
+          sleep 2
+        done
+        if [ $( docker inspect --format "{{`{{.State.Running}}`}}" dataweek_model )" = "true" ]
+        then
+          echo "dataweek_model running already"
+        else
+          docker run {{.DOCKER_ARGS}} --rm -d --name dataweek_model \
+            --network {{.MODEL_DOCKER_NETWORK}} \
+            -v {{.PWD}}/{{.MODEL_DIR}}/:/graph \
+            {{.FUSEKI_IMAGE}} \
+            /jena-fuseki/fuseki-server --tdb2 --file=/graph/{{.GRAPH_FILE}}.nt /model || echo "inspect dataweek_model: not found"
+        fi
     status:
       - '[ "$( docker inspect --format "{{`{{.State.Running}}`}}" dataweek_model )" = "true" ]'
 
